### ISSUE TITLE
Feature: declareAtom API

### ISSUE THREAD

**Issue by NEWESTERS** [nanostores/react#21]
I'd like to propose new API: `declareAtom` function.

It creates shortcuts to pass shared store through context instead of creating sigletons.

Demo: https://codesandbox.io/s/nanostores-di-fvnibt?file=/src/App.tsx

Also there can be function `declareComputed`. With combination of these tools you can model your dataflow and instantiate it only in component tree.

**Comment by ai** [comment]
Can you explain why you think this API is better?

Maybe I miss something. For me, it looks the same, but have an unnecessary building to React.

```js
const Text = declareAtom("Nanostores");

const Input = () => {
  const [text, setText] = Text.useState();

  return (
    <input value={text} onChange={(event) => setText(event.target.value)} />
  );
};
```

```js
const Text = atom("Nanostores");

const Input = () => {
  const [text] = useStore(Text);

  return (
    <input value={text} onChange={(event) => Text.set(event.target.value)} />
  );
};
```

**Comment by ai** [comment]
We have store factory already in Nano Stores ≤0.7 and found that users don’t understand how to use it.

Since it is easy to create a factory we decided to remove confusing API. Advanced users, who need factory will create it with 5 lines of code.

You can release your React-centric helpers as a separated npm project, and we will promote it.

Right now I don’t see how this API will work:
1. It will confuse users again, since the difference between factory and atom is not clear for most users
2. React-centric API is against the ideology of the core tools.
